### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by Invader444** [Shopify/polaris#245]
# Issue summary

## Expected behavior

The build should have completed successfully.

## Actual behavior

The build fails.
<details>$ npm run-script build

> @shopify/polaris@1.9.1 prebuild C:\Users\Jon\workspace\git\polaris
> npm-run-all clean optimize

> @shopify/polaris@1.9.1 clean C:\Users\Jon\workspace\git\polaris
> rimraf build build-esnext esnext styles types docs 'build-intermediate' 'index                                                    .*' 'embedded.js' 'styles.{css,scss}'

> @shopify/polaris@1.9.1 optimize C:\Users\Jon\workspace\git\polaris
> node ./scripts/optimize.js

> @shopify/polaris@1.9.1 build C:\Users\Jon\workspace\git\polaris
> babel-node ./scripts/build.js

'.' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:614
    throw err;
    ^

Error: Command failed: ./node_modules/.bin/tsc --outDir C:\Users\Jon\workspace\g                                                    it\polaris\build-intermediate
    at checkExecSyncError (child_process.js:574:11)
    at execSync (child_process.js:611:13)
    at Object.<anonymous> (C:/Users/Jon/workspace/git/polaris/scripts/build.js:2                                                    2:1)
    at Module._compile (module.js:641:30)
    at loader (C:\Users\Jon\workspace\git\polaris\node_modules\babel-register\li                                                    b\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Jon\wor                                                    kspace\git\polaris\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @shopify/polaris@1.9.1 build: `babel-node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @shopify/polaris@1.9.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                    ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jon\AppData\Roaming\npm-cache\_logs\2017-12-25T18_52_54_27                                                    2Z-debug.log</details>

## Steps to reproduce the problem

1. Clone the repository
1. run npm install
1. run npm run-script build

## Specifications

- Polaris version: 1.9.1
- React version: 16.2.0
- Browser: n/a
- Device: PC
- Operating System: Windows 7 64-bit

---

**Comment by kaelig** [comment]
Thank you for your fix! Your PR is being reviewed and the fix will be published in the next version of Polaris.

**Comment by kaelig** [comment]
Update: the fix was applied and it will be made available in the next release of Polaris. Stay tuned!
