### ISSUE TITLE
warnings on Range Finder ?

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris#379]
# Issue summary

Just added latest Polaris to a project (2.4)

Received lots of warnings about mis-scoped values.

## Expected behavior

Should compile without a lot of warnings.

## Actual behavior

Lots of warnings like this:

webpacker.1 | WARNING in ./node_modules/css-loader??ref--1-2!./node_modules/postcss-loader/lib??ref--1-3!./node_modules/@shopify/polaris/styles.css
webpacker.1 | (Emitted value instead of an instance of Error) postcss-custom-properties: /Users/dlazar/Documents/Workspace/Apps/tonic-living-2018/node_modules/@shopify/polaris/styles.css:3912:3: Custom property ignored: not scoped to the top-level :root element (.Polaris-RangeSlider__Input { ... --progress-lower: ... })
webpacker.1 | NonErrorEmittedError: (Emitted value instead of an instance of Error) postcss-custom-properties: /Users/dlazar/Documents/Workspace/Apps/tonic-living-2018/node_modules/@shopify/polaris/styles.css:3912:3: Custom property ignored: not scoped to the top-level :root element (.Polaris-RangeSlider__Input { ... --progress-lower: ... })
webpacker.1 |     at Object.emitWarning (/Users/dlazar/Documents/Workspace/Apps/tonic-living-2018/node_modules/webpack/lib/NormalModule.js:117:16)
webpacker.1 |     at result.warnings.forEach (/Users/dlazar/Documents/Workspace/Apps/tonic-living-2018/node_modules/postcss-loader/lib/index.js:146:49)
webpacker.1 |     at Array.forEach (<anonymous>)
webpacker.1 |     at postcss.process.then (/Users/dlazar/Documents/Workspace/Apps/tonic-living-2018/node_modules/postcss-loader/lib/index.js:146:27)
webpacker.1 |     at <anonymous>
webpacker.1 |  @ ./node_modules/@shopify/polaris/styles.css 2:14-119
webpacker.1 |  @ ./app/javascript/packs/application.js
webpacker.1 |  @ multi (webpack)-dev-server/client?https://localhost:3032 ./app/javascript/packs/application.js
webpacker.1 |
## Steps to reproduce the problem

Add latest Polaris to a project, and run webpack

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.4
- Browser: Chrome 67
- Device: computer
- Operating System: OSX

**Comment by BPScott** [comment]
This issue is a duplicate of #441.

We have resolved this in 9abe512, which shall be released as part of Polaris 3.0 within the next week or so.

Until then you will have to disable custom-properties transpilation within postcss-preset-env. See https://github.com/Shopify/polaris-react/issues/441#issuecomment-429490870 instructions on how to do that if you're using create-react-app
